site:
  title: ownCloud Desktop Client Documentation
  url: https://doc.owncloud.com

content:
  sources:
  - url: .
    branches:
    - HEAD

ui:
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
    experimental: ''
    # delete block
    latest-version: 2.8
    previous-version: 2.7
    # delete block
    latest-desktop-version: 2.8
    previous-desktop-version: 2.7
  extensions:
    - ./lib/extensions/tabs.js
    - ./node_modules/asciidoctor-kroki/src/asciidoctor-kroki.js
